# coupledL2-test-l2l3
[tltest.config]
core                        = 1
core.tl_c                   = 1
core.tl_ul                  = 1
core.tl_m                   = 2
memory.start                = 0x00000000
memory.end                  = 0x80000000

[tltest.sequence]
mode.0                      = TRACE_WITH_FENCE
mode.1                      = TRACE_WITH_FENCE
mode.2                      = TRACE_WITH_FENCE
mode.3                      = TRACE_WITH_FENCE

[tltest.fuzzer]
trace.file.path             = /nfs/home/zhangyukun/HBL2-Test/NEMU-Matrix/line_trace.txt