# coupledL2-test-l2l3
[tltest.config]
core                        = 1
core.tl_c                   = 1
core.tl_ul                  = 1
core.tl_m                   = 8
# core.tl_lv                   = 8

[tltest.fuzzer]
# Trace file path for fuzzer (default: /nfs/home/chenxi/Matrix/NEMU-Matrix/line_trace.txt)
# trace.file.path             = /path/to/your/trace/file.txt