# coupledL2-test-l2l3
[tltest.config]
core                        = 1
core.tl_c                   = 1
core.tl_ul                  = 1
core.tl_m                   = 8
# core.tl_lv                   = 8

[tltest.sequence]
# MAgent id starting from 2
mode.2                      = TRACE_WITH_FENCE
mode.3                      = TRACE_WITH_FENCE
mode.4                      = TRACE_WITH_FENCE
mode.5                      = TRACE_WITH_FENCE
mode.6                      = TRACE_WITH_FENCE
mode.7                      = TRACE_WITH_FENCE
mode.8                      = TRACE_WITH_FENCE
mode.9                      = TRACE_WITH_FENCE

[tltest.fuzzer]
# trace.file.path             = /path/to/your/trace/file.txt   # do not need to be wrapped in ""
