# coupledL2-test-matrix round2: only MFuzzer active
[tltest.config]
core                        = 1
core.tl_c                   = 1
core.tl_ul                  = 1
core.tl_m                   = 1
maximum_cycle               = 300000

[tltest.sequence]
mode.0                      = PASSIVE
mode.1                      = PASSIVE
mode.2                      = FUZZ_ARI

[tltest.fuzzer]
ari.interval                = 2000
ari.target                  = 2
